config/routes.rb
Rails.application.routes.draw do
  get 'qrcodes/new'
  get 'qrcodes/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "qrcodes#new"
end

app/models/qrcode.rb
class Qrcode
    def initialize(url)
      @url = url
    end

    def generate_qrcode
      qrcode = RQRCode::QRCode.new(@url)

      qrcode_img = qrcode.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: "black",
        file: nil,
        fill: "white",
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 300
        )
        file_name = "#{SecureRandom.hex(32)}.png"
        qrcode_src = "generated/#{file_name}"
        
        IO.binwrite("public/#{qrcode_src}", qrcode_img.to_s)
        
        qrcode_absolute = "/#{qrcode_src}"
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qrcodes_controller.rb
class QrcodesController < ApplicationController
  def new
  end

  def show
    qrcode_params = params[:content].to_s
    qrcode_file = Qrcode.new(qrcode_params)
    @qrcode = qrcode_file.generate_qrcode
    
    respond_to do |format|
      format.json { render :json => {qrcode: "#{root_url}#{qrcode_src}"}, status: :ok }
      format.html { render :show, notice: "Your QRCode was GRACEFFULY generated!" }
    end
    
    # cleaup this file after some seconds timeout

    # arrumar um jeito de enviar como api aqui

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qrcode_helper.rb
module QrcodeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="">
  <head>
    <title>QrcodeGen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--- stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" -->
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body style="">
    <%= render 'shared/header' %>
    <main class="container mx-auto px-2 sm:px-5 flex h-full">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/qrcode/new.html.erb
<div class="mt-28 flex flex-col w-full h-full justify-center items-center">
  <h1 class="text-xl sm:text-2xl mb-12">Generate a new QRCODE!</h1>

  <%= form_tag :qrcode_show, method: :get, class: '' do |f| %>
    <div class="field flex flex-col text-center">
      <%= label_tag 'enter your text or url', nil, class: 'text-gray-500' %>
      <%= text_field_tag :content, nil, required: true, placeholder: 'https://example.com', class: 'rounded-md' %>
    </div>

    <div class="actions mt-4">
      <%= submit_tag 'Generate QRCODE', class: 'px-4 py-2 w-full bg-blue-500 text-white rounded-md cursor-pointer' %>
    </div>
  <% end %>
</div>

app/views/qrcode/show.html.erb
<div class="mt-18 flex flex-col w-full h-full justify-center items-center">
  <div class="text-center">
    <h1 class="text-2xl">Here's your QRCODE!</h1>
    <h2>Share it anywhere</h2>
    <div class="mb-2 pb-4 flex flex-col justify-center items-center shadow-lg rounded-md" style="box-shadow: 2px 2px 5px black; padding: 4px;">
      <img src="<%= @qrcode %>" alt="generated qrcode">
      <div class="flex justify-center items-center">
        <ul class="flex space-x-2 qr-actions">
          <li>
            <%= link_to @qrcode, download: 'generated-qrcode', class: 'bg-blue-500 focus:bg-blue-800 hover:text-blue-800 rounded-full', width: '100px', height: '100px' do %>
              <%= image_tag asset_path('download.png'), alt: 'download' %>
            <% end %>
          </li>
          <li>
            <%= link_to @qrcode, download: 'generated-qrcode', class: 'bg-blue-500 focus:bg-blue-800 hover:text-blue-800 rounded-full', width: '100px', height: '100px' do %>
              <%= image_tag asset_path('print.png'), alt: 'print' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <%= link_to 'Generate new QRCode', qrcode_new_path, class: 'text-blue-500 focus:text-blue-800 hover:text-blue-800' %>
  </div>
</div>

app/views/qrcodes/new.html.erb
<div class="mt-28 flex flex-col w-full h-full justify-center items-center">
  <h1 class="text-xl sm:text-2xl mb-12">Generate a new QRCODE!</h1>

  <%= form_tag :qrcodes_show, method: :get, class: '' do |f| %>
    <div class="field flex flex-col text-center">
      <%= label_tag 'enter your text or url', nil, class: 'text-gray-500' %>
      <%= text_field_tag :content, nil, required: true, placeholder: 'https://example.com', class: 'rounded-md' %>
    </div>

    <div class="actions mt-4">
      <%= submit_tag 'Generate QRCODE', class: 'px-4 py-2 w-full bg-blue-500 text-white rounded-md cursor-pointer' %>
    </div>
  <% end %>
</div>

app/views/qrcodes/show.html.erb
<div class="mt-18 flex flex-col w-full h-full justify-center items-center">
  <div class="text-center">
    <h1 class="text-2xl">Here's your QRCODE!</h1>
    <h2>Share it anywhere</h2>
    <div class="mb-2 pb-4 flex flex-col justify-center items-center shadow-lg rounded-md">
      <img src="<%= @qrcode %>" alt="generated qrcode">
      <div class="flex justify-center items-center">
        <ul class="flex space-x-2 qr-actions">
          <li>
            <%= link_to @qrcode, download: 'generated-qrcode', class: 'bg-blue-500 focus:bg-blue-800 hover:text-blue-800 rounded-full', width: '100px', height: '100px' do %>
              <%= image_tag asset_path('download.png'), alt: 'download' %>
            <% end %>
          </li>
          <li>
            <%= link_to @qrcode, download: 'generated-qrcode', class: 'bg-blue-500 focus:bg-blue-800 hover:text-blue-800 rounded-full', width: '100px', height: '100px' do %>
              <%= image_tag asset_path('print.png'), alt: 'print' %>
            <% end %>
          </li>
          <li>
            <%= link_to @qrcode, download: 'generated-qrcode', class: 'bg-blue-500 focus:bg-blue-800 hover:text-blue-800 rounded-full', width: '100px', height: '100px' do %>
              <%= image_tag asset_path('zapzap.png'), alt: 'whatsapp' %>
            <% end %>
          </li>
          <li>
            <%= link_to @qrcode, download: 'generated-qrcode', class: 'bg-blue-500 focus:bg-blue-800 hover:text-blue-800 rounded-full', width: '100px', height: '100px' do %>
              <%= image_tag asset_path('insta.png'), alt: 'insta' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <%= link_to 'Generate new QRCode', qrcodes_new_path, class: 'text-blue-500 focus:text-blue-800 hover:text-blue-800' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="w-full px-4 py-3 flex flex-col justify-center items-center" style="position:fixed; bottom: -5px;">
  <p class="text-sm text-gray-500">© <%= Date.current.year %> QRCodgen - All reserved rights</p>
</div>

app/views/shared/_header.html.erb
<div class="flex px-6 py-4 w-full mb-2 shadow-sm">
  <%= link_to qrcodes_new_path do %>
    <%= image_tag asset_path('icons8-barcode-48.png'), size: 24 %>
  <% end %>
</div>